# Generated by Django 4.2.13 on 2024-07-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_auto_20240705_2055'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jarcount',
            index=models.Index(fields=['timestamp'], name='counter_jar_timesta_1ae7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='jarcount',
            index=models.Index(fields=['shift'], name='counter_jar_shift_ba3f88_idx'),
        ),
    ]
