# Generated by Django 4.2.13 on 2024-07-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_shifttiming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarcount',
            name='shift1_start',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='jarcount',
            name='shift2_start',
            field=models.TimeField(default='20:00'),
        ),
    ]
