# Generated by Django 4.2.13 on 2024-07-05 20:55
from django.db import migrations

def update_jarcount_inventory(apps, schema_editor):
    JarCount = apps.get_model('counter', 'JarCount')
    Inventory = apps.get_model('counter', 'Inventory')
    default_inventory = Inventory.objects.first()  # Get the first inventory item

    for jarcount in JarCount.objects.all():
        jarcount.inventory = default_inventory
        jarcount.save()

class Migration(migrations.Migration):
    dependencies = [
        ('counter', '0002_inventory_jarcount_inventory'),
    ]

    operations = [
        migrations.RunPython(update_jarcount_inventory),
    ]
