# Generated by Django 4.2.13 on 2024-07-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_jarcount_counter_jar_timesta_1ae7c9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jarcount',
            name='inventory',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
