# Generated by Django 4.2.13 on 2024-07-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(choices=[('Jars', 'Jars'), ('Lids', 'Lids'), ('Labels', 'Labels'), ('Boxes', 'Boxes'), ('Sugar', 'Sugar'), ('Salt', 'Salt'), ('Soy', 'Soy'), ('Peanuts', 'Peanuts')], max_length=100, unique=True)),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='jarcount',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counter.inventory'),
        ),
    ]
